
abstract class FFAppConstants {
  static const String Token =
      'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQ2hhcmxpZSBXaWxsaWFtcyIsImJpcnRoZGF5IjoiMTk3Ny0wMS0yMiIsInBob25lIjoiKDYzMCkgODEzNDQzNyIsImVtYWlsIjoiY2hhcmxpZS53aWxsaWFtc0BkZW1vLmNvbSJ9.uQ4R0-BGx0qHyGsKwYZmo7QxkAvUwNvmRM3py5DPNls';
}
